pipeline:
  deploy:
    image: appleboy/drone-ssh
    host: explorer.iex.ec
    username: ubuntu
    secrets: [ ssh_key, docker_username, docker_password ]
    envs: [ docker_username, docker_password ]
    port: 22
    script:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - DEBUG=* docker run --network="webproxy" --rm iexechub/iexec-dapps-store-updater https://raw.githubusercontent.com/iExecBlockchainComputing/iexec-dapps-store-db/master/dapps-db.js --download
