dappsDB = [
  {
    name: 'Request Network',
    price: 0,
    author: 'Request Network Foundation',
    license: 'MIT',
    excerpt: 'A decentralized network built on top of Ethereum, which allows anyone, anywhere to request a payment.',
    description: 'Request is a decentralized network that allows anyone to request a payment (a Request Invoice)for which the recipient can pay in a secure way. All of the information is stored in a decentralized authentic ledger. This results in cheaper, easier, and more secure payments, and it allows for a wide range of automation possibilities.',
    chains: {},
    social: {
      website: 'https://request.network',
      github: 'https://github.com/RequestNetwork',
      twitter: 'https://twitter.com/requestnetwork',
      medium: 'https://blog.request.network/',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/nMuVjb/request.png',
  },
  {
    name: 'Signals Network',
    price: 1,
    author: 'Signals Network Inc',
    license: 'MIT',
    excerpt: 'Signals is an easy to use platform where you can assemble crypto trading strategies driven by machine learning.',
    description: 'Signals is an easy to use platform where you can assemble crypto trading strategies driven by machine learning - with zero programming skills needed. You can also offer your strategy for copytrading or discover other successful strategies. The crypto currency market is booming and becomes more and more complex. At the same time, more and more people are becoming cryptotraders. Most people nowadays rely on nothing but their gut. We’re big fans of crypto trading, however we’re not gamblers. We don’t want to rely on human emotions and cognitive bias when we know that machine intelligence can solve this problem. Therefore we want to connect data science commmunity with developers and cryptocurrency traders and build a platform that would be easy to use for anyone.',
    chains: {},
    social: {
      website: 'https://signals.network/',
      github: 'https://github.com/signalsnetwork',
      linkedin: 'https://www.linkedin.com/company/18227093/',
      twitter: 'https://twitter.com/signals_network',
      medium: 'https://blog.signals.network/',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/kZeKcw/signals.png',
  },
  {
    name: 'Sudoku',
    frontend: 'https://github.com/iExecBlockchainComputing/iexec-sdk',
    price: 1,
    author: 'Hadrien Croubois',
    license: 'MIT',
    excerpt: 'A sudoku solving algorithm that solves all valid Sudoku puzzles that have a unique solution.',
    description: 'A sudoku is a logic-based, combinatorial number-placement puzzle. The objective is to fill a 9×9 grid with digits so that each column, each row, and each of the nine 3×3 subgrids that compose the grid contains all of the digits from 1 to 9. The puzzle setter provides a partially completed grid, which for a well-posed puzzle has a single solution. Our sudoku solving algorithm can solve any valid Sudoku puzzle that have a unique solution.',
    chains: { mainnet: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba', ropsten: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'https://en.wikipedia.org/wiki/Sudoku',
      github: 'https://github.com/iExecBlockchainComputing/iexec-dapp-samples',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/cAoqjb/sudoku.png',
  },
  {
    name: 'ffmpeg',
    frontend: 'https://github.com/iExecBlockchainComputing/iexec-sdk',
    price: 1,
    author: 'Jeremy Toussaint',
    license: 'MIT',
    excerpt: 'The ffmpeg command line program for transcoding multimedia files.',
    description: 'FFmpeg is a command-line tool that converts audio or video formats. It can also capture and encode in real-time from various hardware and software sources such as a TV capture card.',
    chains: { rinkeby: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'http://ffmpeg.org/',
      github: 'https://github.com/iExecBlockchainComputing/iexec-dapp-samples/tree/ffmpeg',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/i2QEAG/ffmpeg.png',
  },
  {
    name: 'Factorial',
    frontend: 'https://github.com/iExecBlockchainComputing/iexec-dapp-samples/tree/factorial',
    price: 1,
    author: 'François Branciard',
    license: 'MIT',
    excerpt: 'Factorial allows you to calculate the mathematical factorial of a non-negative integer n.',
    description: 'The factorial operation is encountered in many areas of mathematics, notably in combinatorics, algebra, and mathematical analysis. n! is the product of all positive integers less than or equal to n.',
    chains: { ropsten: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'https://en.wikipedia.org/wiki/Factorial',
      github: 'https://github.com/iExecBlockchainComputing/iexec-dapp-samples/tree/ffmpeg',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/ihMXxw/factorial.png',
  },
  {
    name: 'Stockfish',
    frontend: 'https://github.com/iExecBlockchainComputing/iexec-sdk',
    price: 1,
    author: 'iExec',
    license: 'MIT',
    excerpt: 'Stockfish is a powerful and open-source chess engine.',
    description: 'Stockfish is a free and open-source UCI chess engine. Stockfish is one of the strongest chess engines in the world. It is also much stronger than the best human chess grandmasters.',
    chains: { kovan: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'https://stockfishchess.org/',
      github: 'https://github.com/iExecBlockchainComputing/iexec-dapp-samples/tree/stockfish',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/bEAsxw/stockfish.png',
  },
  {
    name: 'Synergy Crowds',
    price: 1,
    author: 'Synergy Crowds',
    license: 'MIT',
    excerpt: 'TBA',
    description: 'TBA',
    chains: {},
    social: {
      website: 'http://synergycrowds.io',
      linkedin: 'https://www.linkedin.com/company/synergycrowds-blockchain',
      twitter: 'https://twitter.com/iex_ec',
      medium: 'https://medium.com/iex-ec',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/nP0gqG/synergy_crowds.png',
  },
  {
    name: 'Vanitygen',
    frontend: 'https://github.com/iExecBlockchainComputing/iexec-sdk',
    price: 1,
    author: 'François Branciard',
    license: 'MIT',
    excerpt: 'Vanitygen is a command-line vanity bitcoin address generator.',
    description: 'If you are tired of the random, cryptic addresses generated by regular bitcoin clients, you can use vanitygen to create a more personalized address. Vanitygen accepts as input a pattern, or list of patterns to search for, and produces a list of addresses and private keys. The search of Vanitygen is probabilistic, and the amount of time required to find a given pattern depends on how complex the pattern is, the speed of your computer, and whether you get lucky.',
    chains: { ropsten: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'https://en.bitcoin.it/wiki/Vanitygen',
      github: 'https://github.com/iExecBlockchainComputing/iexec-dapp-samples/tree/vanitygen',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/gpwzcw/vanity_gen.png',
  },
  {
    name: 'Flixxo',
    price: 1,
    author: 'Flixxo',
    license: '',
    excerpt: 'A decentralized video distribution network, where users will be the owners and beneficiaries of their content.',
    description: 'Flixxo is a a decentralized video distribution network, where users will be the owners and beneficiaries of their content. The platform eliminates intermediaries by letting advertisers, viewers, and content creators engage with each other directly.',
    chains: { ropsten: '' },
    social: {
      website: 'https://www.flixxo.com/',
      github: '',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://tokenmarket.net/blockchain/ethereum/assets/flixxo/logo_big.png',
  },
];
