dappsDB = [
  {
    name: 'Request Network',
    price: 0,
    author: 'Request Network Foundation',
    license: 'MIT',
    excerpt: 'This is an excerpt of the long description of this wonderful app, this will be displayed on the homepage',
    description: 'Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est.',
    chains: {},
    social: {
      website: 'https://request.network',
      github: 'https://github.com/RequestNetwork',
      twitter: 'https://twitter.com/requestnetwork',
      medium: 'https://blog.request.network/',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/nMuVjb/request.png',
  },
  {
    name: 'Signals Network',
    price: 1,
    author: 'Signals Network Inc',
    license: 'MIT',
    excerpt: 'This is an excerpt of the long description of this wonderful app, this will be displayed on the homepage',
    description: 'Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. ',
    chains: {},
    social: {
      website: 'https://signals.network/',
      github: 'https://github.com/signalsnetwork',
      linkedin: 'https://www.linkedin.com/company/18227093/',
      twitter: 'https://twitter.com/signals_network',
      medium: 'https://blog.signals.network/',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/kZeKcw/signals.png',
  },
  {
    name: 'Sudoku',
    frontend: 'https://github.com/iExecBlockchainComputing/iexec-sdk',
    price: 1,
    author: 'Hadrien Croubois',
    license: 'MIT',
    excerpt: 'This is an excerpt of the long description of this wonderful app, this will be displayed on the homepage',
    description: 'Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. ',
    chains: { mainnet: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba', ropsten: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'https://en.wikipedia.org/wiki/Sudoku',
      github: 'https://github.com/iExecBlockchainComputing/iexec-dapp-samples',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/cAoqjb/sudoku.png',
  },
  {
    name: 'ffmpeg',
    frontend: 'https://github.com/iExecBlockchainComputing/iexec-sdk',
    price: 1,
    author: 'Jeremy Toussaint',
    license: 'MIT',
    excerpt: 'This is an excerpt of the long description of this wonderful app, this will be displayed on the homepage',
    description: 'Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. ',
    chains: { rinkeby: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'http://ffmpeg.org/',
      github: 'https://github.com/iExecBlockchainComputing/iexec-dapp-samples/tree/ffmpeg',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/i2QEAG/ffmpeg.png',
  },
  {
    name: 'Factorial',
    frontend: 'https://github.com/iExecBlockchainComputing/iexec-dapp-samples/tree/factorial',
    price: 1,
    author: 'François Branciard',
    license: 'MIT',
    excerpt: 'In mathematics, the factorial of a non-negative integer n, denoted by n!, is the product of all positive integers less than or equal to n.',
    description: 'The factorial operation is encountered in many areas of mathematics, notably in combinatorics, algebra, and mathematical analysis. Its most basic occurrence is the fact that there are n! ways to arrange n distinct objects into a sequence (i.e., permutations of the set of objects). This fact was known at least as early as the 12th century, to Indian scholars.[2] Fabian Stedman, in 1677, described factorials as applied to change ringing.',
    chains: { ropsten: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'https://en.wikipedia.org/wiki/Factorial',
      github: 'https://github.com/iExecBlockchainComputing/iexec-dapp-samples/tree/ffmpeg',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/ihMXxw/factorial.png',
  },
  {
    name: 'Stockfish',
    frontend: 'https://github.com/iExecBlockchainComputing/iexec-sdk',
    price: 1,
    author: 'iExec',
    license: 'MIT',
    excerpt: 'Stockfish is one of the strongest chess engines in the world. It is also much stronger than the best human chess grandmasters.',
    description: 'Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. ',
    chains: { kovan: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'https://stockfishchess.org/',
      github: 'https://github.com/iExecBlockchainComputing/iexec-dapp-samples/tree/stockfish',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/bEAsxw/stockfish.png',
  },
  {
    name: 'Synergy Crowds',
    price: 1,
    author: 'Synergy Crowds',
    license: 'MIT',
    excerpt: 'This is an excerpt of the long description of this wonderful app, this will be displayed on the homepage',
    description: 'Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. ',
    chains: {},
    social: {
      website: 'http://synergycrowds.io',
      linkedin: 'https://www.linkedin.com/company/synergycrowds-blockchain',
      twitter: 'https://twitter.com/iex_ec',
      medium: 'https://medium.com/iex-ec',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/nP0gqG/synergy_crowds.png',
  },
  {
    name: 'Vanitygen',
    frontend: 'https://github.com/iExecBlockchainComputing/iexec-sdk',
    price: 1,
    author: 'François Branciard',
    license: 'MIT',
    excerpt: 'This is an excerpt of the long description of this wonderful app, this will be displayed on the homepage',
    description: 'Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. ',
    chains: { ropsten: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'https://en.bitcoin.it/wiki/Vanitygen',
      github: 'https://github.com/iExecBlockchainComputing/iexec-dapp-samples/tree/vanitygen',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/gpwzcw/vanity_gen.png',
  },
];
