dappsDB = [
  {
    name: 'Request',
    frontend: 'https://iex.ec',
    price: 1,
    author: 'Request Inc',
    license: 'MIT',
    excerpt: 'This is an excerpt of the long description of this wonderful app, this will be displayed on the homepage',
    description: 'Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. ',
    chains: { ropsten: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'htts://iex.ec',
      github: 'https://github.com/iExecBlockchainComputing',
      linkedin: 'https://fr.linkedin.com/company/iex.ec',
      twitter: 'https://twitter.com/iex_ec',
      medium: 'https://medium.com/iex-ec',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/nMuVjb/request.png',
  },
  {
    name: 'Signals',
    frontend: 'https://iex.ec',
    price: 1,
    author: 'Signals Inc',
    license: 'MIT',
    excerpt: 'This is an excerpt of the long description of this wonderful app, this will be displayed on the homepage',
    description: 'Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. ',
    chains: { rinkeby: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'htts://iex.ec',
      github: 'https://github.com/iExecBlockchainComputing',
      linkedin: 'https://fr.linkedin.com/company/iex.ec',
      twitter: 'https://twitter.com/iex_ec',
      medium: 'https://medium.com/iex-ec',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/kZeKcw/signals.png',
  },
  {
    name: 'sudoku',
    frontend: 'https://iex.ec',
    price: 1,
    author: 'Hadrien Croubois',
    license: 'MIT',
    excerpt: 'This is an excerpt of the long description of this wonderful app, this will be displayed on the homepage',
    description: 'Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. ',
    chains: { mainnet: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba', ropsten: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'htts://iex.ec',
      github: 'https://github.com/iExecBlockchainComputing',
      linkedin: 'https://fr.linkedin.com/company/iex.ec',
      twitter: 'https://twitter.com/iex_ec',
      medium: 'https://medium.com/iex-ec',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/cAoqjb/sudoku.png',
  },
  {
    name: 'ffmpeg',
    frontend: 'https://iex.ec',
    price: 1,
    author: 'Jeremy Toussaint',
    license: 'MIT',
    excerpt: 'This is an excerpt of the long description of this wonderful app, this will be displayed on the homepage',
    description: 'Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. ',
    chains: { rinkeby: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'htts://iex.ec',
      github: 'https://github.com/iExecBlockchainComputing',
      linkedin: 'https://fr.linkedin.com/company/iex.ec',
      twitter: 'https://twitter.com/iex_ec',
      medium: 'https://medium.com/iex-ec',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/i2QEAG/ffmpeg.png',
  },
  {
    name: 'factorial',
    frontend: 'https://iex.ec',
    price: 1,
    author: 'François Branciard',
    license: 'MIT',
    excerpt: 'This is an excerpt of the long description of this wonderful app, this will be displayed on the homepage',
    description: 'Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. ',
    chains: { ropsten: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'htts://iex.ec',
      github: 'https://github.com/iExecBlockchainComputing',
      linkedin: 'https://fr.linkedin.com/company/iex.ec',
      twitter: 'https://twitter.com/iex_ec',
      medium: 'https://medium.com/iex-ec',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/ihMXxw/factorial.png',
  },
  {
    name: 'stockfish',
    frontend: 'https://iex.ec',
    price: 1,
    author: 'iExec',
    license: 'MIT',
    excerpt: 'This is an excerpt of the long description of this wonderful app, this will be displayed on the homepage',
    description: 'Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. ',
    chains: { kovan: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'htts://iex.ec',
      github: 'https://github.com/iExecBlockchainComputing',
      linkedin: 'https://fr.linkedin.com/company/iex.ec',
      twitter: 'https://twitter.com/iex_ec',
      medium: 'https://medium.com/iex-ec',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/bEAsxw/stockfish.png',
  },
  {
    name: 'Synergy Crowds',
    frontend: 'https://iex.ec',
    price: 1,
    author: 'Mircea',
    license: 'MIT',
    excerpt: 'This is an excerpt of the long description of this wonderful app, this will be displayed on the homepage',
    description: 'Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. ',
    chains: { mainnet: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba', kovan: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'htts://iex.ec',
      github: 'https://github.com/iExecBlockchainComputing',
      linkedin: 'https://fr.linkedin.com/company/iex.ec',
      twitter: 'https://twitter.com/iex_ec',
      medium: 'https://medium.com/iex-ec',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/nP0gqG/synergy_crowds.png',
  },
  {
    name: 'Vanitygen',
    frontend: 'https://iex.ec',
    price: 1,
    author: 'Eduardo El Gringo',
    license: 'MIT',
    excerpt: 'This is an excerpt of the long description of this wonderful app, this will be displayed on the homepage',
    description: 'Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. Mauris a nunc occideritis me rectum. Videtur quod Ive facillimum, qui fecit vos. Potes me interficere, sine testibus et tunc manere in pauci weeks vel mensis vestigia Isai Pinkman et vos quoque illum occidere. Exercitium inutili option A. Videtur mihi quod autem est. ',
    chains: { ropsten: '0xa25ad4fcb247e63ee528ca2475c3eb6e0db94da3123d3f9d351648a7fac825ba' },
    social: {
      website: 'htts://iex.ec',
      github: 'https://github.com/iExecBlockchainComputing',
      linkedin: 'https://fr.linkedin.com/company/iex.ec',
      twitter: 'https://twitter.com/iex_ec',
      medium: 'https://medium.com/iex-ec',
    },
    created: '2017-12-02T19:45:33.044Z',
    logo: 'https://image.ibb.co/gpwzcw/vanity_gen.png',
  },
];
